# name: ci pipeline

# on: push

# jobs:
#     project-testing:
#         runs-on: ubuntu-latest

#         steps:
#             - name: checkout code
#               uses: actions/checkout@v3

#             - name: setup python
#               uses: actions/setup-python@v2
#               with:
#                 python-version: "3.10"

#             - name: install dependencies
#               env:
#                 DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
#               run:
#                 pip install -r requirements.txt

#             - name: run pipeline 
#               run: |
#                  dvc repro

name: CI Pipeline

on: push

jobs:
    project-testing:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Set DAGSHUB_PAT as Environment Variable
              env:
                DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
              run: echo "DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }}" >> $GITHUB_ENV

            - name: Verify Environment Variable
              run: echo "DAGSHUB_PAT is set!"

            - name: Run Pipeline
              run: dvc repro
